### ISSUE TITLE
Support automatic theme changes

### ISSUE THREAD

**Issue by dzikoysk** [iBavtovich/day-and-night-plugin#1]
![obraz](https://user-images.githubusercontent.com/4235722/57045691-ba575a00-6c6e-11e9-9398-79b317d58ef2.png)

**Comment by iBavtovich** [comment]
Hello @dzikoysk! 
Sorry for late answer. Can you please clarify why do you need such opportunity?

**Comment by iBavtovich** [comment]
I find only one case: when you want to switch between next schemes: both dark or both bright. In this case whole appearance and color scheme don't change. Seems like a bug :)

**Comment by dzikoysk** [comment]
The Day And Night plugin changes only color scheme for editor:
![obraz](https://user-images.githubusercontent.com/4235722/57719305-c0dace00-767f-11e9-8256-7aa7d0df63ab.png)
But it the latest version of IntelliJ it is common also to change the whole theme of IJ (because there is a lot of new plugins around new api):
![obraz](https://user-images.githubusercontent.com/4235722/57719376-e8319b00-767f-11e9-9515-c7910fb6f206.png)

I think it could be great to support **both**, the color scheme and theme in your day-night cycle:
![obraz](https://user-images.githubusercontent.com/4235722/57719470-1dd68400-7680-11e9-93ba-fdadbf3261a9.png)

**Comment by iBavtovich** [comment]
Thanks for detailed comment! I will take a look more closely at this and implement this feature soon :)

**Comment by iBavtovich** [comment]
@dzikoysk feature was implemented. Plugin is available in JetBrains Plugins Repository now. Update and enjoy it :)
