### ISSUE TITLE
Theme changes also changes the editor color scheme

### ISSUE THREAD

**Issue by onewildgamer** [iBavtovich/day-and-night-plugin#11]
When the theme changes, the color scheme of the editor also changes. I have `Solarised Light` editor color scheme with the  `macOS light` theme. During the switch back to `macOS light` theme from `Dracula`, the editor color scheme changes to `Intellij Light`. I wish to retain the editor color scheme of my preference.

**Comment by dzikoysk** [comment]
You should be able to select editor scheme associated with a theme in the plugin configuration section.

**Comment by iBavtovich** [comment]
Hi! @onewildgamer did you solve the problem with settings?

**Comment by onewildgamer** [comment]
Yes @iBavtovich I solved it with recent updates to the plugin.
