### ISSUE TITLE
Incompatible to new UI of PyCharm 2023.1

### ISSUE THREAD

**Issue by danschef** [iBavtovich/day-and-night-plugin#15]
This plugin does not seem to be compatible anymore with the new UI of PyCharm 2023.1. The icon of the day-and-night-plugin does not show up and also the automatic switch between the day and night theme does not work.

**Comment by iBavtovich** [comment]
Hi @danschef! Thanks for your feedback and sorry for long delay: are you still experiencing issues?

**Comment by aleaforny** [comment]
Hi @iBavtovich, I was also concerned by the problem with PyCharm 2023.1, but I tested again with PyCharm 2023.2 and it works like a charm.

Thanks

**Comment by danschef** [comment]
Yes, I also can confirm that everything works well again with PyCharm 2024.2.1. Thanks!
