### ISSUE TITLE
Support manual switching between day and night mode

### ISSUE THREAD

**Issue by dzikoysk** [iBavtovich/day-and-night-plugin#3]
We have different days or mood. Sometimes it is sunny, sometimes it is cloudy. I think it could be great to be able to change day/night mode using icon from the bottom toolbar:

![obraz](https://user-images.githubusercontent.com/4235722/58094367-cd57ad00-7bd0-11e9-82a9-654c440e9ce0.png)

Black, alpha-based image could fit great to the rest of the icons:

![obraz](https://user-images.githubusercontent.com/4235722/58094407-e4969a80-7bd0-11e9-84fd-a746ec049292.png)

It also may become the logo:

![obraz](https://user-images.githubusercontent.com/4235722/58094558-422ae700-7bd1-11e9-8d72-dd30521a471d.png)

**Comment by iBavtovich** [comment]
Sounds great! I will take it to the work :) Thanks

**Comment by iBavtovich** [comment]
Feature was implemented :) plugin is available for update. Enjoy!
