### ISSUE TITLE
Doesn't appear to change automatically

### ISSUE THREAD

**Issue by flukejones** [iBavtovich/day-and-night-plugin#4]
By this I mean I have had CLion open for a few hours with plugin set up. When my local time changed to the time specified for night-time theme change, it didn't change the theme. But if I restart the app it does change.

Not really sure what other details I can provide for you here.

**Comment by dzikoysk** [comment]
Did you try to set `current time + 1 minute` to check if it works at any time?

**Comment by Luke-Nukem** [comment]
Hmm, I'm not sure why, but *after* I did that, auto-change started working correctly. Sorry it didn't cross my mind to do this first.

**Comment by Luke-Nukem** [comment]
It fails to change after resuming from hibernation. Not sure about sleep as my laptop fails to boot from sleep.
I'm not familiar with Java at all,  but I imagine maybe it's to do with a frozen timer or thread? Manually changing the time fixes it until the next hibernation.

Linux distro - Ubuntu 19.04

**Comment by iBavtovich** [comment]
Hi!
Yep, I know this issue. I will check what can do with this problem. In the nearest future I am going to add possibility to switch scheme manually. 
So it can be used as temporary workaround :)
Thanks for details!

**Comment by iBavtovich** [comment]
@Luke-Nukem if you update plugin you will be able now to switch between schemes using small icon in IDE status bar. If you face with this bug again, you can use this feature

**Comment by iBavtovich** [comment]
Better late than never! Fixed that issue in version 1.2.4. Will be available for upgrade/download in 1-2 days :)
