### ISSUE TITLE
When switching themes, switch to night theme in the evening and day theme in the morning

### ISSUE THREAD

**Issue by DBalobanov** [iBavtovich/day-and-night-plugin#7]
Currently when switch time comes it just alternates selected theme.
For example if I switch to dark theme manually ahead of schedule, when time comes for automatic switch, it switches me back to light scheme instead of just doing nothing...

Hopefully it's an easy fix.
Otherwise plugin works perfectly and is very useful.
Thank you.

**Comment by iBavtovich** [comment]
Hi @DBalobanov!
Thank you for your feedback. Can you please provide information about which version do you use? Which IDE or tool?
Because, as for now - everything should work as you expected.

**Comment by DBalobanov** [comment]
Hello Ignat,

It was broken when I created the issue, but it seems to be working fine now. Hopefully it was a glitch or something. Though I’m quite confident it happened few times to me before.

I’m using Rider 2019.3.1 and most recent version of your plugin.

Sorry for false alarm 😊

With best regards,
Dmitry.

**Comment by iBavtovich** [comment]
No problem! In any case - thanks for feedback about plugun =)

**Comment by DBalobanov** [comment]
Hello Ignat,

This morning it switched me to night scheme. I have two instances of Rider running, not sure if it is making a difference. Both switched to night scheme.

My settings:
[cid:image001.png@01D5BA35.E8ACA800]


[cid:image002.png@01D5BA35.E8ACA800]

[cid:image003.png@01D5BA35.E8ACA800]

With best regards,
Dmitry
