### ISSUE TITLE
Update for version 2020.1

### ISSUE THREAD

**Issue by 1chriis1** [iBavtovich/day-and-night-plugin#8]
The plugin is now incompatible with version 2020.1

**Comment by iBavtovich** [comment]
Hi, new version will be available in marketplace for update in 2 days :)

**Comment by 1chriis1** [comment]
That's awesome! Thank you very much.
This is quite my favorite plugin and I only found out about it a couple weeks ago!
Thanks for that and the hard work!

**Comment by iBavtovich** [comment]
Version 1.2.3 is available in the Intelij Marketplace. Enjoy :)

**Comment by 1chriis1** [comment]
@iBavtovich thank you so much!
Out of curiosity, do you have to update your plugin for every new release?

**Comment by iBavtovich** [comment]
> Out of curiosity, do you have to update your plugin for every new release?

@1chriis1 At least for now this version should work for all release until the end of 2020. But if some of the used in plugin API will be deleted in 2020.2 - 2020.4, I have to update it. 
Also I would like to made some non-functional improvements of the plugin, so there age going to be some updates in the upcoming year.

**Comment by 1chriis1** [comment]
Thanks a lot for your hard work!

**Comment by dzikoysk** [comment]
I think it could be a good idea to replace `until-build` with `since-build` like that:

https://github.com/dzikoysk/carbon-theme/commit/04b68af0fffed9f9e7f50a416e7e72a44e463c81

In most cases we can assume that API didn't change

**Comment by iBavtovich** [comment]
@dzikoysk You are right :) thanks, will remove `until-build` tag in future
