### ISSUE TITLE
The plugin throws the following exception every time IntelliJ Idea starts.

### ISSUE THREAD

**Issue by 1chriis1** [iBavtovich/day-and-night-plugin#9]
I've included the exception in the following .txt file. 
[exception.txt](https://github.com/iBavtovich/day-and-night-plugin/files/4496794/exception.txt)

**Comment by iBavtovich** [comment]
@1chriis1 hi! Thanks, will look into it :)

**Comment by iBavtovich** [comment]
Fixed, version 1.2.4 will be available in 2 days in Marketplace.

**Comment by 1chriis1** [comment]
Thanks a lot!
